---
title: "Evaluation graphs with different seeds and train/test ratios"
author: "Kayla Frisoli"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  hide
---


\ 
&nbsp;
\ 
&nbsp;

```{r, warning=FALSE}

library(ggplot2)
library(reshape2)

```

# Block = first letter of first name, Seed = 2468 {.tabset}

## Test/Train Ratio 20:80

```{r}

f1data2080 <- read.csv("~/Documents/CMU/Census/Package/BasicRL/evaluationgraphs/f1data2080.csv")
f1data2080 <- f1data2080[, -1]
f1data2080.long <- melt(f1data2080, id="n")  # convert to long format

f1plot2080 <- ggplot(data=f1data2080.long, aes(x=n, y=value, colour=variable)) +
              geom_line() +
              ggtitle("set.seed = 2468, test/train = 20:80") +
              scale_color_discrete("Evaluation Errors")

f1plot2080

```

## Test/Train Ratio 50:50

```{r}

f1data5050 <- read.csv("~/Documents/CMU/Census/Package/BasicRL/evaluationgraphs/f1data5050.csv")
f1data5050 <- f1data5050[, -1]
f1data5050.long <- melt(f1data5050, id="n")  # convert to long format

f1plot5050 <- ggplot(data=f1data5050.long, aes(x=n, y=value, colour=variable)) +
              geom_line() +
              ggtitle("set.seed = 2468, test/train = 50:50") +
              scale_color_discrete("Evaluation Errors")
f1plot5050

```


## Test/Train Ratio 80:20

```{r}

f1data8020 <- read.csv("~/Documents/CMU/Census/Package/BasicRL/evaluationgraphs/f1data8020.csv")
f1data8020 <- f1data8020[, -1]
f1data8020.long <- melt(f1data8020, id="n")  # convert to long format

f1plot8020 <- ggplot(data=f1data8020.long, aes(x=n, y=value, colour=variable)) +
              geom_line() +
              ggtitle("set.seed = 2468, test/train = 80:20") +
              scale_color_discrete("Evaluation Errors")
f1plot8020

```

# Block = first letter of first name, Seed = 9 {.tabset}

## Test/Train Ratio 20:80

```{r}

f1data2080NewSeed <- read.csv("~/Documents/CMU/Census/Package/BasicRL/evaluationgraphs/f1data2080NewSeed.csv")
f1data2080NewSeed <- f1data2080NewSeed[, -1]
f1data2080NewSeed.long <- melt(f1data2080NewSeed, id="n")  # convert to long format

f1plot2080NewSeed <- ggplot(data=f1data2080NewSeed.long, aes(x=n, y=value, colour=variable)) +
                     geom_line() +
                     ggtitle("set.seed = 9, test/train = 20:80") +
                     scale_color_discrete("Evaluation Errors")

f1plot2080NewSeed

```

## Test/Train Ratio 50:50

```{r}

f1data5050NewSeed <- read.csv("~/Documents/CMU/Census/Package/BasicRL/evaluationgraphs/f1data5050NewSeed.csv")
f1data5050NewSeed <- f1data5050NewSeed[, -1]
f1data5050NewSeed.long <- melt(f1data5050NewSeed, id="n")  # convert to long format

f1plot5050NewSeed <- ggplot(data=f1data5050NewSeed.long, aes(x=n, y=value, colour=variable)) +
                     geom_line() +
                     ggtitle("set.seed = 9, test/train = 50:50") +
                     scale_color_discrete("Evaluation Errors")

f1plot5050NewSeed

```



## Test/Train Ratio 80:20

```{r}

f1data8020NewSeed <- read.csv("~/Documents/CMU/Census/Package/BasicRL/evaluationgraphs/f1data8020NewSeed.csv")
f1data8020NewSeed <- f1data8020NewSeed[, -1]
f1data8020NewSeed.long <- melt(f1data8020NewSeed, id="n")  # convert to long format

f1plot8020NewSeed <- ggplot(data=f1data8020NewSeed.long, aes(x=n, y=value, colour=variable)) +
                     geom_line() +
                     ggtitle("set.seed = 9, test/train = 80:20") +
                     scale_color_discrete("Evaluation Errors")

f1plot8020NewSeed

```


# Block = birth month, Seed = 2468 {.tabset}

## Test/Train Ratio 10:90

```{r}

bm2data1090 <- read.csv("~/Documents/CMU/Census/Package/BasicRL/evaluationgraphs/bm2data1090.csv")
bm2data1090 <- bm2data1090[, -1]
bm2data1090.long <- melt(bm2data1090, id="n")  # convert to long format

bm2plot1090 <- ggplot(data=bm2data1090.long, aes(x=n, y=value, colour=variable)) +
              geom_line() +
              ggtitle("set.seed = 2468, test/train = 10:90") +
              scale_color_discrete("Evaluation Errors")

bm2plot1090

```

## Test/Train Ratio 50:50

```{r}

bm2data5050 <- read.csv("~/Documents/CMU/Census/Package/BasicRL/evaluationgraphs/bm2data5050.csv")
bm2data5050 <- bm2data5050[, -1]
bm2data5050.long <- melt(bm2data5050, id="n")  # convert to long format

bm2plot5050 <- ggplot(data=bm2data5050.long, aes(x=n, y=value, colour=variable)) +
              geom_line() +
              ggtitle("set.seed = 2468, test/train = 50:50") +
              scale_color_discrete("Evaluation Errors")

bm2plot5050

```

## Test/Train Ratio 90:10

```{r}

bm2data9010 <- read.csv("~/Documents/CMU/Census/Package/BasicRL/evaluationgraphs/bm2data9010.csv")
bm2data9010 <- bm2data9010[, -1]
bm2data9010.long <- melt(bm2data9010, id="n")  # convert to long format

bm2plot9010 <- ggplot(data=bm2data9010.long, aes(x=n, y=value, colour=variable)) +
              geom_line() +
              ggtitle("set.seed = 2468, test/train = 90:10") +
              scale_color_discrete("Evaluation Errors")

bm2plot9010

```


